= Performance Benchmark

This module contains a performance benchmark, which measures the time spent by TRIO while computing
robustness metrics. 

This benchmark proceeds in two steps:

. Generate graphs randomly , whose size varies between 1 and 2500 vertices. These 
graphs are generated by a separate R script and serialized on disk in separate CSV files.

. The TRIO benchmark, per se, transforms these random graphs into TRIO topologies, and compute 
all robustness metrics, while measuring the time spent on each graph.

CAUTION: Running this benchmark will consume time and disk space. The generation and analysis of 
graphs will *takes around two hours*, depending on the underlying power, and the graphs serialized on 
disk will *need around 2 GB of memory*.

== Generating Random Graphs

The generation of random graphs is done by a separate R script, built upon the 
link:http://igraph.org/r/[iGraph library]. It covers the generation of three main families of graphs, namely:

* Erdos-Renyi graphs, which are graphs whose edges are created with a fixed probability. 

* Small-world graphs, which are graphs where the distance between all pair of nodes remains below a 
given threshold. These are generated using the Watts & Strogatz model.

* Scale-free graphs, where a few nodes have significantly more connexions than the others. They are 
generated by using the Barabasi & Albert model. 

The generation of random graphs encompasses the computation of several topological
metrics, including density, diameter, average node degree, and several measures of centrality. 

The graphs are identified by a single natural number and saved as edge lists in separate CSV files.

== Running the Performance Benchmark

The benchmark per se is a regular Java application which can be run from the command line, as shown 
below.

.Sample output of the performance benchmark, run from the command line
----
$> java -cp "bin/*" eu.diversify.trio.performance.Runner
TRIO - Topology Robustness Indicator
Copyright (C) 2015 - SINTEF ICT

Reading configuration in 'setup.properties'
 - 50 topologies(s) ;
 - from files 'graph_%d.csv' in './graphs' ;
 - 15 % as warmup.


Warming-up ...
Progress: 100 % [avg. duration =  322.55 ms]

Evaluating performance ...
Progress: 100 % [avg. duration =  360.45 ms]

That's all folks!
----

== Tuning the Benchmark

The performance benchmark include a warmup time, which ensure that the underlying JIT compiler of 
the JVM has enough time to compile the code, and stabilize the performance measures. The number of 
graphs used in the warmup phase, as well as other parameters, can be overriden in the 
'setup.properties' file, as shown below:

.Sample 'setup.properties' which controls the behaviour of the benchmark
[source,property]
----
# The ID of the first graph to process
first.graph.id = 1

# The ID of the last graph to process
last.graph.id = 100

# The directory that contains all the graphs
graph.directory = ./graphs

# The pattern that characterize the name of files containing a graph
graph.file.pattern = graph_%d.csv

# The percentatge of graph to use as warmup for the JVM
warmup.ratio = 0.05
----
